/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import { TypedEventFilter, TypedEvent, TypedListener } from "./commons";

interface StringTestInterface extends ethers.utils.Interface {
  functions: {
    "testString()": FunctionFragment;
    "testString2()": FunctionFragment;
    "testString3()": FunctionFragment;
    "testUnicodeString()": FunctionFragment;
    "testUnicodeString2()": FunctionFragment;
    "testUnicodeString3()": FunctionFragment;
    "testUnicodeString4()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "testString",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testString2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testString3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testUnicodeString",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testUnicodeString2",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testUnicodeString3",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "testUnicodeString4",
    values?: undefined
  ): string;

  decodeFunctionResult(functionFragment: "testString", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "testString2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testString3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnicodeString",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnicodeString2",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnicodeString3",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testUnicodeString4",
    data: BytesLike
  ): Result;

  events: {};
}

export class StringTest extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: StringTestInterface;

  functions: {
    testString(overrides?: CallOverrides): Promise<[BigNumber]>;

    testString2(overrides?: CallOverrides): Promise<[BigNumber]>;

    testString3(overrides?: CallOverrides): Promise<[BigNumber]>;

    testUnicodeString(overrides?: CallOverrides): Promise<[BigNumber]>;

    testUnicodeString2(overrides?: CallOverrides): Promise<[BigNumber]>;

    testUnicodeString3(overrides?: CallOverrides): Promise<[BigNumber]>;

    testUnicodeString4(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  testString(overrides?: CallOverrides): Promise<BigNumber>;

  testString2(overrides?: CallOverrides): Promise<BigNumber>;

  testString3(overrides?: CallOverrides): Promise<BigNumber>;

  testUnicodeString(overrides?: CallOverrides): Promise<BigNumber>;

  testUnicodeString2(overrides?: CallOverrides): Promise<BigNumber>;

  testUnicodeString3(overrides?: CallOverrides): Promise<BigNumber>;

  testUnicodeString4(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    testString(overrides?: CallOverrides): Promise<BigNumber>;

    testString2(overrides?: CallOverrides): Promise<BigNumber>;

    testString3(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString2(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString3(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString4(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    testString(overrides?: CallOverrides): Promise<BigNumber>;

    testString2(overrides?: CallOverrides): Promise<BigNumber>;

    testString3(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString2(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString3(overrides?: CallOverrides): Promise<BigNumber>;

    testUnicodeString4(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    testString(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testString2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testString3(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testUnicodeString(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    testUnicodeString2(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testUnicodeString3(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    testUnicodeString4(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
