/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { MockEmpty, MockEmptyInterface } from "../MockEmpty";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50603f80601d6000396000f3fe6080604052600080fdfea264697066735822122068516e2a050f734a5a66788208aef294a7871e7324afe3344e1e63ae39f3925764736f6c63430008070033";

export class MockEmpty__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MockEmpty> {
    return super.deploy(overrides || {}) as Promise<MockEmpty>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MockEmpty {
    return super.attach(address) as MockEmpty;
  }
  connect(signer: Signer): MockEmpty__factory {
    return super.connect(signer) as MockEmpty__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockEmptyInterface {
    return new utils.Interface(_abi) as MockEmptyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockEmpty {
    return new Contract(address, _abi, signerOrProvider) as MockEmpty;
  }
}
