/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { StringTest, StringTestInterface } from "../StringTest";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "testString",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "testString2",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "testString3",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "testUnicodeString",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "testUnicodeString2",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "testUnicodeString3",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "testUnicodeString4",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101dc806100206000396000f3fe608060405234801561001057600080fd5b506004361061006d5760003560e01c80630909ce68146100725780635ea5445a146100a957806371a483b7146100d05780637ae76b43146100f5578063e2fab2c11461011c578063f18c825114610157578063fb8f0f5914610190575b600080fd5b6100976000604051806040016040528060018152602001603160f81b81525051905090565b60405190815260200160405180910390f35b61009760006040518060400160405280600381526020016231003160e81b81525051905090565b6100976000604051806040016040528060018152602001601960f91b81525051905090565b610097600060405180604001604052806003815260200162e6889160e81b81525051905090565b6100976000604051806040016040528060178152602001761cd1123cf1163cb192eb861c97559cb4953cb5d13d32f5604b1b81525051905090565b6100976000604051806040016040528060158152602001741cd1123cf1163cb192fc97559cb4953cb5d13d32f5605b1b81525051905090565b604080516020810190915260009081905261009756fea26469706673582212205febb86777494eda9ddaac80b4c21fbd6b9ea6187e2c02b4d1da5cb915e9b66c64736f6c63430008040033";

export class StringTest__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<StringTest> {
    return super.deploy(overrides || {}) as Promise<StringTest>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): StringTest {
    return super.attach(address) as StringTest;
  }
  connect(signer: Signer): StringTest__factory {
    return super.connect(signer) as StringTest__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): StringTestInterface {
    return new utils.Interface(_abi) as StringTestInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): StringTest {
    return new Contract(address, _abi, signerOrProvider) as StringTest;
  }
}
